name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      # Verify Salesforce CLI
      - name: Verify Salesforce CLI
        run: |
          sf --version

      # Decrypt JWT Key
      - name: Decrypt JWT Key
        run: |
          openssl enc -nosalt -aes-256-cbc -d \
            -in keys/server.key.enc \
            -base64 \
            -K ${{ secrets.ENCRYPTION_KEY }} \
            -iv ${{ secrets.ENCRYPTION_IV }} \
            -out keys/server.key

      # Authenticate Salesforce Org
      - name: Authenticate Salesforce Org
        run: |
          sf org login jwt \
            --client-id "${{ secrets.CONSUMER_KEY }}" \
            --jwt-key-file keys/server.key \
            --username "${{ secrets.SF_USERNAME }}" \
            --instance-url "https://login.salesforce.com" \
            --alias "devorg"

      # Display Connected Orgs
      - name: Display Org List
        run: |
          sf org list

      # Deploy Salesforce Metadata
      - name: Deploy Metadata
        run: |
          sf project deploy start --source-dir force-app