name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SF_CLIENT_ID: ${{ secrets.CONSUMER_KEY }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      SF_ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        shell: bash
        run: |
          npm install sfdx-cli --global

      # Verify Salesforce CLI
      - name: Verify Salesforce CLI
        shell: bash
        run: |
          sfdx --version

      # Decrypt JWT Key
      - name: Decrypt JWT Key
        shell: bash
        run: |
          openssl enc -nosalt -aes-256-cbc -d \
          -in keys/server.key.enc \
          -out keys/server.key \
          -base64 \
          -K $SF_ENCRYPTION_KEY \
          -iv $SF_ENCRYPTION_IV

      # Authenticate Salesforce Org
      - name: Authenticate Salesforce Org
        shell: bash
        run: |
          sfdx force:auth:jwt:grant \
          --clientid $SF_CLIENT_ID \
          --jwtkeyfile keys/server.key \
          --username $SF_USERNAME \
          --instanceurl https://login.salesforce.com \
          --setdefaultusername \
          --setalias devorg

      # Display Connected Orgs
      - name: Display Org List
        shell: bash
        run: |
          sfdx force:org:list

      # Deploy Metadata
      - name: Deploy Metadata
        shell: bash
        run: |
          sfdx force:source:deploy -p force-app -u devorg